# Generated by Django 3.2.18 on 2023-04-21 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('Udate', models.DateTimeField(auto_now=True)),
                ('customer_id', models.AutoField(db_column='customer_id', primary_key=True, serialize=False)),
                ('customer_xid', models.TextField(db_column='customer_xid', db_index=True, unique=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('cdate', models.DateTimeField(auto_created=True)),
                ('Udate', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(db_column='wallet_id', max_length=10, primary_key=True, serialize=False)),
                ('status', models.BooleanField(db_column='status', default=False)),
                ('enabled_at', models.DateTimeField()),
                ('balance', models.FloatField(default=0, max_length=20)),
                ('owned_by', models.OneToOneField(db_column='owned_by_id', on_delete=django.db.models.deletion.DO_NOTHING, to='wallet_app.customer')),
            ],
            options={
                'db_table': 'wallet',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_created=True)),
                ('Udate', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('Withdrawal', 'Withdrawal'), ('Deposit', 'Deposit')], db_column='transaction_type', max_length=30)),
                ('amount', models.FloatField(max_length=20)),
                ('transacted_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(db_column='wallet_id', on_delete=django.db.models.deletion.CASCADE, to='wallet_app.wallet')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
