# Generated by Django 3.2.18 on 2023-04-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Udate',
            new_name='udate',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='Udate',
            new_name='udate',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='Udate',
            new_name='udate',
        ),
        migrations.AlterField(
            model_name='customer',
            name='cdate',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
