# Generated by Django 3.2.18 on 2023-04-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0002_auto_20230421_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='cdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
